### ISSUE TITLE
[v1.0.0] getAllDataForKey crash

### ISSUE THREAD

**Issue by kolyneh** [sunnylqm/react-native-storage#216] opened 2019-03-28 09:25 UTC
使用` v1.0.0 `版本出现 getAllDataForKey crash，错误信息如下：
`
undefined is not an object (evaluating '_this._m.__keys__')
`
退回`v0.2.4`版本就没问题。

**Comment by juhasuni** [comment] 2019-04-11 11:50
The problem is, that `getAllDataForKey` calls `getIdsForKey`, which in turn doesn't wait for the internal `_mapPromise` to resolve and for that reason `this._m` is undefined. In order to fix it, the `getIdsForKey` needs to be changed asynchronous and it must wait for the internal `_mapPromise` to be resolved, like most other async methods do. The documentation actually already says that `getIdsForKey` returns a Promise, but it doesn't.

As a workaround, you can call `load` before `getAllDataForKey`, like this:

```
try { await storage.load({key}); } catch(e) {};
let data = await storage.getAllDataForKey(key);
```

**Comment by sunnylqm** [comment] 2019-04-11 13:27
That's true. Thanks for reminding! @juhasuni

**Comment by sunnylqm** [comment] 2019-04-11 14:05
Should be fixed in https://github.com/sunnylqm/react-native-storage/commit/adfcc82beca1c50238c8d71d8d913aa308e67140

**Closed by sunnylqm** 2019-04-11 14:05 UTC
